#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF5BE8B267C6A406D (bruno@clisp.org)
#
Name     : libunistring
Version  : 1.1
Release  : 21
URL      : https://mirrors.kernel.org/gnu/libunistring/libunistring-1.1.tar.xz
Source0  : https://mirrors.kernel.org/gnu/libunistring/libunistring-1.1.tar.xz
Source1  : https://mirrors.kernel.org/gnu/libunistring/libunistring-1.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: libunistring-info = %{version}-%{release}
Requires: libunistring-lib = %{version}-%{release}
Requires: libunistring-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glibc-locale

%description
GNU LIBUNISTRING - Unicode string library
This library provides functions for manipulating Unicode strings and
for manipulating C strings according to the Unicode standard.

%package dev
Summary: dev components for the libunistring package.
Group: Development
Requires: libunistring-lib = %{version}-%{release}
Provides: libunistring-devel = %{version}-%{release}
Requires: libunistring = %{version}-%{release}

%description dev
dev components for the libunistring package.


%package dev32
Summary: dev32 components for the libunistring package.
Group: Default
Requires: libunistring-lib32 = %{version}-%{release}
Requires: libunistring-dev = %{version}-%{release}

%description dev32
dev32 components for the libunistring package.


%package doc
Summary: doc components for the libunistring package.
Group: Documentation
Requires: libunistring-info = %{version}-%{release}

%description doc
doc components for the libunistring package.


%package info
Summary: info components for the libunistring package.
Group: Default

%description info
info components for the libunistring package.


%package lib
Summary: lib components for the libunistring package.
Group: Libraries
Requires: libunistring-license = %{version}-%{release}

%description lib
lib components for the libunistring package.


%package lib32
Summary: lib32 components for the libunistring package.
Group: Default
Requires: libunistring-license = %{version}-%{release}

%description lib32
lib32 components for the libunistring package.


%package license
Summary: license components for the libunistring package.
Group: Default

%description license
license components for the libunistring package.


%prep
%setup -q -n libunistring-1.1
cd %{_builddir}/libunistring-1.1
pushd ..
cp -a libunistring-1.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666025159
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check
cd ../build32;
make check || :

%install
export SOURCE_DATE_EPOCH=1666025159
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libunistring
cp %{_builddir}/libunistring-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libunistring/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libunistring-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/libunistring/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/unicase.h
/usr/include/uniconv.h
/usr/include/unictype.h
/usr/include/unigbrk.h
/usr/include/unilbrk.h
/usr/include/uniname.h
/usr/include/uninorm.h
/usr/include/unistdio.h
/usr/include/unistr.h
/usr/include/unistring/cdefs.h
/usr/include/unistring/iconveh.h
/usr/include/unistring/inline.h
/usr/include/unistring/localcharset.h
/usr/include/unistring/stdbool.h
/usr/include/unistring/stdint.h
/usr/include/unistring/version.h
/usr/include/unistring/woe32dll.h
/usr/include/unitypes.h
/usr/include/uniwbrk.h
/usr/include/uniwidth.h
/usr/lib64/libunistring.so

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libunistring.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libunistring/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/libunistring.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libunistring.so.5
/usr/lib64/libunistring.so.5.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libunistring.so.5
/usr/lib32/libunistring.so.5.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libunistring/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/libunistring/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
